### ISSUE TITLE
CakePHP 3 dev dependency

### ISSUE THREAD

**Issue by btaens** [guemidiborhane/Cake-Yaml#3]
The plugin has __cakephp/cakephp: 3.0.*-dev__ as a dependency, which causes problems when trying to use the stable version of CakePHP 3. It should just have __cakephp/cakephp: ~3.0__ as a dependency.

**Comment by guemidiborhane** [comment]
FIxed thank you for the reminder

**Comment by btaens** [comment]
Make sure to update packagist as well.

**Comment by guemidiborhane** [comment]
created a new release thank you
